# -*- coding: utf-8 -*-
"""notebook04ef0043aa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HrdsKpVl2WtCkhdjQsfCvP4mzUNaCDnl
"""

import numpy as np
import pandas as pd
import os

data=pd.read_csv('WHR2024.csv')
df=data.head(25)
df

import matplotlib.pyplot as plt
x=df['Country name']
y=df['Ladder score']
color = ['lightblue', 'blue', 'purple', 'red', 'black']
plt.figure(figsize=(11,6))
plt.xticks(rotation=45, ha='right', fontsize=8)
bars=plt.bar(x,y,color=color)
for bar in bars:
    height = bar.get_height()
    plt.text(bar.get_x() + bar.get_width() / 2, height, str(int(height)), ha='center', va='bottom')
plt.xlabel('Countries')
plt.ylabel('ladder index')
plt.ylim(top=10)
plt.tight_layout()
plt.title('Top 25 WHR countries')
plt.show()

y=df['Explained by: Log GDP per capita']
plt.figure(figsize=(11,6))
plt.xticks(rotation=45, ha='right', fontsize=8)

bars=plt.bar(x,y,color=color)
for bar in bars:
    height = bar.get_height()
    plt.text(bar.get_x() + bar.get_width() / 2, height, str((height)), ha='center', va='bottom',rotation=45)
plt.xlabel('Countries')
plt.ylabel('Social Support')
plt.ylim(top=3)
plt.tight_layout()
plt.title('Top 25 WHR countries,GDP per capita')
plt.show()
print("Ok so money is great")

y=df['Explained by: Social support']


plt.figure(figsize=(11,6))
plt.xticks(rotation=45, ha='right', fontsize=8)

bars=plt.bar(x,y,color=color)
for bar in bars:
    height = bar.get_height()
    plt.text(bar.get_x() + bar.get_width() / 2, height, str((height)), ha='center', va='bottom',rotation=45)
plt.xlabel('Countries')
plt.ylabel('Social Support')
plt.ylim(top=2)
plt.tight_layout()
plt.title('Top 25 WHR countries,social support')
plt.show()
print('So the social support is less significant in happiness index')

y=df['Explained by: Healthy life expectancy']
plt.figure(figsize=(11,6))
plt.xticks(rotation=45, ha='right', fontsize=8)

bars=plt.bar(x,y,color=color)
for bar in bars:
    height = bar.get_height()
    plt.text(bar.get_x() + bar.get_width() / 2, height, str((height)), ha='center', va='bottom',rotation=45)
plt.xlabel('Countries')
plt.ylabel('Life EXPECTENCY')
plt.ylim(top=1)
plt.tight_layout()
plt.title('Top 25 WHR countries,Life expectency')
plt.show()
print("Hapiness increases life expentancy")

y=df['Explained by: Freedom to make life choices']
plt.figure(figsize=(11,6))
plt.xticks(rotation=45, ha='right', fontsize=8)

bars=plt.bar(x,y,color=color)
for bar in bars:
    height = bar.get_height()
    plt.text(bar.get_x() + bar.get_width() / 2, height, str((height)), ha='center', va='bottom',rotation=45)
plt.xlabel('Countries')
plt.ylabel('Freedom of life choices')
plt.ylim(top=1)
plt.tight_layout()
plt.title('Top 25 WHR countries,Freedom to make life choices')
plt.show()
print("Increase in freedom is helpful")

z=df['Explained by: Perceptions of corruption']
y=df['Dystopia + residual']
plt.figure(figsize=(11,6))
plt.xticks(rotation=45, ha='right', fontsize=8)

bars=plt.bar(x,y,color='blue',label='Dystopia')
bars2=plt.bar(x,z,color='red',label='Corruption')
for bar in bars:
    height = bar.get_height()
    plt.text(bar.get_x() + bar.get_width() / 2, height, str((height)), ha='center', va='bottom',rotation=45)
for bar in bars2:
    height = bar.get_height()
    plt.text(bar.get_x() + bar.get_width() / 2, height, str((height)), ha='center', va='bottom',rotation=45)
plt.xlabel('Countries')
plt.ylabel('Freedom of life choices')
plt.ylim(top=7)
plt.title('Top 25 WHR countries,Freedom to make life choices')
plt.tight_layout()
plt.legend()
plt.show()
print("Happy Life also result of low dystopia and corruption")